Remove hard pin on tensorflow-macos requirement
This prevents installation on Python 3.10, as 2.8.0 doesn't support it.

```
ERROR: Cannot install rasa==3.4.0 and tensorflow-macos>=2.11.0 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```